### ISSUE TITLE
Change 'Completable' class name to avoid confusion with rxJava's Completable 

### ISSUE THREAD

**Issue by stepango** [iamironz/binaryprefs#20]

**Comment by iamironz** [comment]
This is part of internal api which is not intended to use in your code. Why you need this? What is your confuse?

**Comment by stepango** [comment]
`Completable` in terms of binary-prefs library is public and could be misused as `org.reactivex.Completable` which is more common.
Also vice-versa situation also could lead to confusion during code-review when binary-prefs `Completable` could be interpreted as `org.reactivex.Completable`

Other solution could be marking `Completable` as private or package private if it's really used as internal api only.

**Comment by iamironz** [comment]
> Completable in terms of binary-prefs library is public and could be misused as org.reactivex.Completable which is more common.
> Also vice-versa situation also could lead to confusion during code-review when binary-prefs Completable could be interpreted as org.reactivex.Completable

Okay, so.. backward question: why rxjava uses `Observable` as public api class name? 
Because Java standard lib has `java.util.Observable` from 1.0, also Android standard lib has `android.database.Observable` from 1 api.

I think this problem is overpriced especially `com.ironz.binaryprefs.task.Completable` is not for your codebase usage. This class never will be in your codebase. Of course this affects IDE auto-completion but it's not argument for renaming non-public library api.

Also try to open an issue in rxjava project with this problem, but answer is obvious =)

>Other solution could be marking Completable as private or package private if it's really used as internal api only.

this is impossible due to `com.ironz.binaryprefs.task.Completable` usages from another library packages.
Class constructor accessor already changed from public to to package-private but it's not in the master branch right now.

--
I think best solution is class renaming but right now I have no idea what can I call this class. Any ideas?

**Comment by iamironz** [comment]
Renamed to `FutureBarrier`

**Comment by iamironz** [comment]
removed into https://github.com/iamironz/binaryprefs/pull/21/files
